const client=supabase.createClient(ZENITH_SUPABASE.url,ZENITH_SUPABASE.publishableKey),loginPanel=document.getElementById("loginPanel"),editorPanel=document.getElementById("editorPanel"),status=document.getElementById("loginStatus"),editorStatus=document.getElementById("editorStatus"),form=document.getElementById("editorForm"),list=document.getElementById("articleList");let editingId=null;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const set=(m,err=false)=>{(editorPanel.hidden?status:editorStatus).textContent=m;(editorPanel.hidden?status:editorStatus).className=err?"status error":"status"};
async function categories(){const{data,error}=await client.from("categories").select("id,name").order("name");if(error)return set(error.message,true);category_id.innerHTML='<option value="">Select category</option>'+(data||[]).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join("")}
async function articles(){const{data,error}=await client.from("articles").select("id,title,published,categories(name)").order("updated_at",{ascending:false});if(error)return set(error.message,true);list.innerHTML=(data||[]).map(x=>`<div class="admin-row"><div><b>${esc(x.title)}</b><small>${esc(x.categories?.name||"Uncategorized")} · ${x.published?"Published":"Draft"}</small></div><button class="button secondary" data-id="${x.id}">Edit</button></div>`).join("")||"<p>No articles yet.</p>";list.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>edit(b.dataset.id))}
async function edit(id){const{data,error}=await client.from("articles").select("*").eq("id",id).single();if(error)return set(error.message,true);editingId=id;["title","slug","excerpt","content","author_name","cover_image","category_id"].forEach(k=>document.getElementById(k).value=data[k]||"");published.checked=!!data.published;deleteBtn.hidden=false;formTitle.textContent="Edit article"}
title.oninput=()=>{if(!editingId)slug.value=title.value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")};
form.onsubmit=async e=>{e.preventDefault();const p={title:title.value.trim(),slug:slug.value.trim(),excerpt:excerpt.value.trim(),content:content.value,author_name:author_name.value.trim()||"Zenith Hackers Intelligence",cover_image:cover_image.value.trim()||null,category_id:category_id.value||null,published:published.checked,published_at:published.checked?new Date().toISOString():null,updated_at:new Date().toISOString()};const r=editingId?await client.from("articles").update(p).eq("id",editingId):await client.from("articles").insert(p);if(r.error)return set(r.error.message,true);set("Saved.");await articles()};
newBtn.onclick=()=>{editingId=null;form.reset();author_name.value="Zenith Hackers Intelligence";deleteBtn.hidden=true;formTitle.textContent="New article";set("")};
deleteBtn.onclick=async()=>{if(!editingId||!confirm("Delete this article permanently?"))return;const{error}=await client.from("articles").delete().eq("id",editingId);if(error)return set(error.message,true);newBtn.click();await articles();set("Deleted.")};
loginForm.onsubmit=async e=>{e.preventDefault();const{error}=await client.auth.signInWithPassword({email:email.value,password:password.value});if(error)return set(error.message,true);init()};
logoutBtn.onclick=async()=>{await client.auth.signOut();location.reload()};
async function init(){const{data:{session}}=await client.auth.getSession();if(!session){loginPanel.hidden=false;editorPanel.hidden=true;return}const{data:admin}=await client.from("admin_users").select("user_id").eq("user_id",session.user.id).maybeSingle();if(!admin){await client.auth.signOut();return set("This account is not an authorized publisher.",true)}loginPanel.hidden=true;editorPanel.hidden=false;await categories();await articles()}init();
