const searchInput=document.getElementById("siteSearch");
const client=window.supabase&&window.ZENITH_SUPABASE?window.supabase.createClient(window.ZENITH_SUPABASE.url,window.ZENITH_SUPABASE.publishableKey):null;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
async function loadArticles(){if(!client)return;const {data,error}=await client.from("articles").select("id,title,slug,excerpt,author_name,cover_image,published_at,categories(name,slug)").eq("published",true).order("published_at",{ascending:false});if(error||!data?.length)return;const grid=document.querySelector(".article-grid");if(!grid)return;grid.innerHTML=data.map(a=>`<article class="article-card glass">${a.cover_image?`<img src="${esc(a.cover_image)}" alt="" loading="lazy">`:""}<span class="tag">${esc(a.categories?.name||"INTELLIGENCE")}</span><h3>${esc(a.title)}</h3><p>${esc(a.excerpt||"Read the latest Zenith Hackers Intelligence analysis.")}</p><small>${a.published_at?esc(new Date(a.published_at).toLocaleDateString()):""}</small><br><a href="article.html?slug=${encodeURIComponent(a.slug)}">Read analysis →</a></article>`).join("");attachSearch()}
function attachSearch(){if(!searchInput)return;const cards=[...document.querySelectorAll(".article-card")];searchInput.oninput=()=>{const q=searchInput.value.toLowerCase().trim();cards.forEach(c=>c.hidden=!!q&&!c.textContent.toLowerCase().includes(q))}}
attachSearch();loadArticles();
document.querySelector(".menu-toggle")?.addEventListener("click",e=>{const n=document.querySelector(".nav");const open=n.style.display==="flex";n.style.display=open?"":"flex";e.currentTarget.setAttribute("aria-expanded",String(!open))});
document.getElementById("year")?.append(new Date().getFullYear());
document.getElementById("subscribeForm")?.addEventListener("submit",e=>{e.preventDefault();document.getElementById("formMessage").textContent="Subscription form is ready for database/email integration."});
document.getElementById("chatForm")?.addEventListener("submit",async e=>{e.preventDefault();const input=document.getElementById("chatInput"),box=document.getElementById("chatMessages"),q=input.value.trim();if(!q)return;const u=document.createElement("div");u.className="chat-msg user";u.textContent=q;box.append(u);input.value="";const a=document.createElement("div");a.className="chat-msg assistant";a.textContent="Thinking…";box.append(a);try{const r=await fetch(`${window.ZENITH_SUPABASE.url}/functions/v1/chat`,{method:"POST",headers:{"Content-Type":"application/json","apikey":window.ZENITH_SUPABASE.publishableKey},body:JSON.stringify({message:q})});const d=await r.json();if(!r.ok)throw Error();a.textContent=d.reply||d.error||"No response received."}catch{a.textContent="The AI assistant needs its Supabase Edge Function deployed and OPENAI_API_KEY configured."}});
